events {
    worker_connections 1024;   
}
http {
  upstream instrutor {
    server worker-patrick:5678;
    server worker-trevisan:5678;
    server worker-don:5678;
  }

  server {
    listen 8000;
    location /aula {
        proxy_pass http://instrutor;
    }
  }
}