events {
    worker_connections 1024;   
}
http {
  upstream instrutor {
    server cristian:5678;
    server beca:5678;
    server helo:5678;
  }

  server {
    listen 8000;
    location /aula {
        proxy_pass http://instrutor;
    }
  }
}